// Code generated by goctl. DO NOT EDIT.
package types

type GenerateCreateTableSqlReq struct {
	TableName string `json:"table_name"`
	Delimiter string `json:"delimiter"`
	Text      string `json:"text"`
}

type GenerateCreateTableSqlResp struct {
	CreateTableSql string `json:"create_table_sql"`
}
